# --------------------------------------------------------------------------------
# Partial Pipeline to deploy all Azure Resources for one environment
# --------------------------------------------------------------------------------
parameters:
  environmentCode: 'dev'
  environmentUpper: 'DEV'
  subscriptionName: 'My Subscription Name (mySubscriptionId)'
  subscriptionId: 'mySubscriptionId'
  resourceGroupName: 'rg_myResourceGroup'
  regionName: 'eastus'
  regionTitle: 'East US'
  orgPrefix: 'org'
  appPrefix: 'app'
  appSuffix: '1'
  iotHubSku: 'S1'
  dpsSku: 'S1'
  webAppSku: 'S1'
  signalRSku: 'F1'
  runDateTime: '12-31-2020 23:59:59'

# --------------------------------------------------------------------------------
jobs:
  - deployment: DeployEnvironment
    displayName: 'Initialize ${{parameters.environmentUpper}} Deploy'
    environment: ${{parameters.environmentUpper}}
  - job: Deploy_${{parameters.environmentUpper}}
    displayName: Deploy ${{parameters.environmentUpper}} Environment
    steps:
    - template: ado_deploy_one_bicepfile.yml # Service Bus
      parameters:
        bicepFileName: 'svcbus'
        sku: ''
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # Iot Hub
      parameters:
        bicepFileName: 'iothub'
        sku: ${{parameters.iotHubSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml #  DPS
      parameters:
        bicepFileName: 'dps'
        sku: ${{parameters.dpsSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: true
    - template: ado_deploy_one_bicepfile.yml # Cosmos Database
      parameters:
        bicepFileName: 'cosmos'
        sku: ''
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # SignalR Hub
      parameters:
        bicepFileName: 'signalr'
        sku: ${{parameters.signalRSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # Streaming Analytics
      parameters:
        bicepFileName: 'streaming'
        sku: ''
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # Function App
      parameters:
        bicepFileName: 'functionapp'
        sku: ''
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # Website Dashboard
      parameters:
        bicepFileName: 'website'
        sku: ${{parameters.webAppSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # KeyVault
      parameters:
        bicepFileName: 'keyvault'
        sku: ${{parameters.webAppSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false
    - template: ado_deploy_one_bicepfile.yml # Event Grid Subscription
      parameters:
        bicepFileName: 'eventGridSubscription'
        sku: ${{parameters.webAppSku}}
        environmentCode: ${{parameters.environmentCode}}
        environmentUpper: ${{parameters.environmentUpper}}
        resourceGroupName: ${{parameters.resourceGroupName}}
        subscriptionName: ${{parameters.subscriptionName}}
        subscriptionId: ${{parameters.subscriptionId}}
        regionName: ${{parameters.regionName}}
        regionTitle: ${{parameters.regionTitle}}
        orgPrefix: ${{parameters.orgPrefix}} 
        appPrefix: ${{parameters.appPrefix}} 
        appSuffix: ${{parameters.appSuffix}}
        runDateTime: ${{parameters.runDateTime}}
        ignoreError: false

