# --------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments for IoT Sample Project
# --------------------------------------------------------------------------------

trigger:
- main

pool:
  vmImage: ubuntu-latest

name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

# --------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  - template: ado_deploy_one_environment.yml
    parameters:
      environmentCode: 'dev'
      environmentUpper: 'DEV'
      resourceGroupName: 'rg_iotdev'
      subscriptionName: 'Lyle''s Primary Subscription (6a97aa36-e4fc-4db0-baa6-4cffaba22e97)'
      subscriptionId: '6a97aa36-e4fc-4db0-baa6-4cffaba22e97'
      regionName: 'eastus'
      regionTitle: 'East US'
      orgPrefix: 'lci'
      appPrefix: 'iot'
      appSuffix: '1'
      iotHubSku: 'F1'
      webAppSku: 'B1'
      signalRSku: 'Free_F1'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: ado_deploy_one_environment.yml
    parameters:
      environmentCode: 'qa'
      environmentUpper: 'QA'
      resourceGroupName: 'rg_iotqa'
      subscriptionName: 'Lyle''s Primary Subscription (6a97aa36-e4fc-4db0-baa6-4cffaba22e97)'
      subscriptionId: '6a97aa36-e4fc-4db0-baa6-4cffaba22e97'
      regionName: 'eastus'
      regionTitle: 'East US'
      orgPrefix: 'lci'
      appPrefix: 'iot'
      appSuffix: '1'
      iotHubSku: 'S1'
      webAppSku: 'S1'
      signalRSku: 'Free_F1'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
