# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources for All Environments for the IoT Demo Project
# ------------------------------------------------------------------------------------------------------------------------
# Note 1: This pipeline needs a variable group "IoTDemo-Infra-<env>" -> for EACH environment -> with these variables:
#   orgPrefix:            '<org / your initials>'
#   appPrefix:            'iotdemo'
#   environmentCode:      'dev/qa/prod'
#   resourceGroupName:    'rg_<prefix>_<envCode>'
#   subscriptionName:     '<ServiceConnectionName / Subscription Name>'
#   subscriptionId:       '<subscriptionId>'
#   location:             'eastus'
#   appSuffix:            ''
#   storageSku:           'Standard_LRS'
#   functionAppSku:       'Y1'
#   functionAppSkuFamily: 'Y'
#   functionAppSkuTier:   'Dynamic'
#   webSiteSku:           'B1'
#   keyVaultOwnerUserId1: '<guid>' // Future: email address
#   keyVaultOwnerUserId2: '<guid>' // Future: email address
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
#trigger: none # only fire this manually
trigger:
  paths:
    include: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- stage: DeployDEVResources
  displayName: DEV Deploy Resources
  jobs:
  # 1. Need a way to create resource group if it doesn't exist...
  # - script: New-AzResourceGroup -Name rg_iotdemo_dev -Location "eastUS"
  #   displayName: Create ResourceGroup

  # 2a. Find a way to get the Owner GUID from AD and pass that into a variable
  # - script: 
  #      Connect-AzureAD
  #      $owner1UserObjectId = (Get-AzureAdUser -ObjectId "lyleluppes@microsoft.com").ObjectId
  #      echo "##vso[task.setvariable variable=owner1UserObjectId]$(owner1UserObjectId)"
  #      $owner2UserObjectId = (Get-AzureAdUser -ObjectId "chrishouse@microsoft.com").ObjectId
  #      echo "##vso[task.setvariable variable=owner2UserObjectId]$(owner1UserObjectId)"
  #   displayName: Get Owner 1 Id
  # 2b. Next step: pass this variable parameter into the Bicep file

  - template: Deploy-Bicep.yml
    parameters:
      variableGroupName: 'IoTDemo-Infra-Dev'
      environmentUpper: 'DEV'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'

# ----------------------------------------------------------------------------------------------------
- stage: DeployQAResources
  displayName: QA Deploy Resources
  dependsOn: DeployDEVResources
  condition: succeeded('DeployDEVResources')
  jobs:
  - template: Deploy-Bicep.yml
    parameters:
      variableGroupName: 'IoTDemo-Infra-QA'
      environmentUpper: 'QA'
      runDateTime: 'Pipeline-$(Build.BuildNumber)'
